// Turns the story scripts in /story into src/game/storyText.js. Run: npm run story
// Write the story in the .md files (see the header comment in story/long.md for the format), then run this.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ACT_MAP = ['calm', 'calm', 'uneasy', 'wrong', 'horror', 'finale']; // Act I..VI -> how wrong the world is
const MAX_PARAGRAPH = 260; // narration lines are grouped into typing paragraphs up to about this many characters

function parse(file) {
  const text = fs.readFileSync(path.join(root, 'story', file), 'utf8').replace(/<!--[\s\S]*?-->/g, '').replace(/\r/g, '');
  const sections = text.split(/^## /m).slice(1);
  if (sections.length !== ACT_MAP.length) throw new Error(`${file}: expected ${ACT_MAP.length} acts, found ${sections.length}`);
  const items = [];
  let ending = 'NEXT DRIVER, PLEASE.';
  sections.forEach((section, i) => {
    const act = ACT_MAP[i];
    const lines = section.split('\n').slice(1).map((l) => l.trim()).filter((l) => l && !l.startsWith('*'));
    let buf = '';
    const flush = () => { if (buf) items.push({ act, kind: 'narration', text: buf }); buf = ''; };
    for (const line of lines) {
      if (/[^\x20-\x7e]/.test(line)) throw new Error(`${file}: non-ASCII character in: ${line}`);
      if (line.includes('`')) throw new Error(`${file}: backtick in: ${line}`);
      const sign = line.match(/^\[sign\]\s*(.+)$/);
      const caps = line === line.toUpperCase() && /[A-Z]/.test(line);
      if (sign || caps) {
        flush();
        if (i === ACT_MAP.length - 1 && line === ending) continue; // shown after the fade, not typed
        items.push({ act, kind: sign ? 'sign' : 'message', text: sign ? sign[1] : line });
      } else if (buf && buf.length + 1 + line.length > MAX_PARAGRAPH) {
        flush();
        buf = line;
      } else {
        buf = buf ? `${buf} ${line}` : line;
      }
    }
    flush();
  });
  return { items, ending };
}

const long = parse('long.md');
const short = parse('short.md');
const fmt = (items) => items.map((p) => `  P(${JSON.stringify(p.act)}, ${JSON.stringify(p.kind)}, ${JSON.stringify(p.text)}),`).join('\n');
const chars = (items) => items.reduce((n, p) => n + p.text.length, 0);

const out = `// GENERATED by scripts/build-story.mjs from story/short.md and story/long.md. Do not edit by hand: edit the scripts and run \`npm run story\`.
const P = (act, kind, text) => ({ act, kind, text });

export const ENDING_LINE = ${JSON.stringify(long.ending)};

export const SHORT = [
${fmt(short.items)}
];

export const LONG = [
${fmt(long.items)}
];
`;
fs.writeFileSync(path.join(root, 'src/game/storyText.js'), out);
for (const [name, s] of [['short', short], ['long', long]]) {
  console.log(`${name}: ${s.items.length} paragraphs, ${chars(s.items)} chars, about ${(chars(s.items) / 5 / 40).toFixed(1)} min at 40 WPM`);
}
